import type { Metadata } from "next";
import { FC, ReactNode } from "react";
import { DM_Sans } from "next/font/google";

const dm_sans = DM_Sans();

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={dm_sans.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
