import { Color } from "../interface";
import clsx from "clsx";

export const coerceTailwindBackground = (color?: Color) => {
  if (!color) return "";

  return clsx({
    "bg-background": color === Color.BACKGROUND,
    "bg-foreground": color === Color.FOREGROUND,
    "bg-divider": color === Color.DIVIDER,
    "bg-focus": color === Color.FOCUS,
    "bg-content1": color === Color.CONTENT1,
    "bg-content2": color === Color.CONTENT2,
    "bg-content3": color === Color.CONTENT3,
    "bg-content4": color === Color.CONTENT4,
    "bg-default": color === Color.DEFAULT,
    "bg-primary": color === Color.DEFAULT_PRIMARY,
    "bg-secondary": color === Color.DEFAULT_SECONDARY,
    "bg-success": color === Color.DEFAULT_SUCCESS,
    "bg-warning": color === Color.DEFAULT_WARNING,
    "bg-danger": color === Color.DEFAULT_DANGER,
    "bg-primary-50": color === Color.PRIMARY_50,
    "bg-primary-100": color === Color.PRIMARY_100,
    "bg-primary-200": color === Color.PRIMARY_200,
    "bg-primary-300": color === Color.PRIMARY_300,
    "bg-primary-400": color === Color.PRIMARY_400,
    "bg-primary-500": color === Color.PRIMARY_500,
    "bg-primary-600": color === Color.PRIMARY_600,
    "bg-primary-700": color === Color.PRIMARY_700,
    "bg-primary-800": color === Color.PRIMARY_800,
    "bg-primary-900": color === Color.PRIMARY_900,
    "bg-secondary-50": color === Color.SECONDARY_50,
    "bg-secondary-100": color === Color.SECONDARY_100,
    "bg-secondary-200": color === Color.SECONDARY_200,
    "bg-secondary-300": color === Color.SECONDARY_300,
    "bg-secondary-400": color === Color.SECONDARY_400,
    "bg-secondary-500": color === Color.SECONDARY_500,
    "bg-secondary-600": color === Color.SECONDARY_600,
    "bg-secondary-700": color === Color.SECONDARY_700,
    "bg-secondary-800": color === Color.SECONDARY_800,
    "bg-secondary-900": color === Color.SECONDARY_900,
    "bg-success-50": color === Color.SUCCESS_50,
    "bg-success-100": color === Color.SUCCESS_100,
    "bg-success-200": color === Color.SUCCESS_200,
    "bg-success-300": color === Color.SUCCESS_300,
    "bg-success-400": color === Color.SUCCESS_400,
    "bg-success-500": color === Color.SUCCESS_500,
    "bg-success-600": color === Color.SUCCESS_600,
    "bg-success-700": color === Color.SUCCESS_700,
    "bg-success-800": color === Color.SUCCESS_800,
    "bg-success-900": color === Color.SUCCESS_900,
    "bg-warning-50": color === Color.WARNING_50,
    "bg-warning-100": color === Color.WARNING_100,
    "bg-warning-200": color === Color.WARNING_200,
    "bg-warning-300": color === Color.WARNING_300,
    "bg-warning-400": color === Color.WARNING_400,
    "bg-warning-500": color === Color.WARNING_500,
    "bg-warning-600": color === Color.WARNING_600,
    "bg-warning-700": color === Color.WARNING_700,
    "bg-warning-800": color === Color.WARNING_800,
    "bg-warning-900": color === Color.WARNING_900,
    "bg-danger-50": color === Color.DANGER_50,
    "bg-danger-100": color === Color.DANGER_100,
    "bg-danger-200": color === Color.DANGER_200,
    "bg-danger-300": color === Color.DANGER_300,
    "bg-danger-400": color === Color.DANGER_400,
    "bg-danger-500": color === Color.DANGER_500,
    "bg-danger-600": color === Color.DANGER_600,
    "bg-danger-700": color === Color.DANGER_700,
    "bg-danger-800": color === Color.DANGER_800,
    "bg-danger-900": color === Color.DANGER_900,
  });
};
